name: Build and deploy training documentation to training.plone.org

on:
  push:
    branches:
      - "main"

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q -r requirements.txt -c constraints.txt
          pip freeze
          sudo snap install --edge vale

      - name: Run Vale
        run: |
          git clone https://github.com/errata-ai/Microsoft.git
          cp -r ./Microsoft/Microsoft ./styles
          VALEFILES=$(find ./docs/ -type f -name "*.md" -print)
          vale --no-exit $VALEFILES

      # TODO Raise linkcheck barrier again.
      # - name: Run linkcheck
      #   run: make linkcheck

      - name: Prepare deploy
        run: make deploy

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY_TRAINING}}
        with:
          flags: "-avzr --delete"
          options: ""
          ssh_options: "-p ${{secrets.DEPLOY_PORT}}"
          src: "_build/html/"
          dest: "${{secrets.DEPLOY_USER_TRAINING}}@${{secrets.DEPLOY_SERVER_TRAINING}}:${{secrets.DEPLOY_PATH_TRAINING}}"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
